# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
# permalink: pretty
# relative_permalinks: true

# Setup
title: TAIS Official Website
tagline: ""
description: ""
url: https://thutais.github.io/
baseurl: /

author:
  name: "Juliana Banos"

paginate: 5

github:
  repo: https://github.com/thutais/thutais.github.io
